### ISSUE TITLE
Initialize fails

### ISSUE THREAD

**Issue by CK90** [jstapels/mpu6050#2]
Hey, I got a problem.

This code works:
var i2c = require('i2c');
var address = 0x68;
var wire = new i2c(address, {device: '/dev/i2c-1'});

But this one not:
var mpu6050  = require( 'mpu6050' );
var mpu = new mpu6050('/dev/i2c-1', 0x68);
if( mpu.initialize() ){
    console.log( "success" );
} else {
    console.log( "fail" );
}

I think there is a problem with the address, but I'm not sure. Can you help  me?

**Comment by jstapels** [comment]
Hrmm, not off the top of my head. The library uses i2c under the covers, so it should being doing essentially the same exact thing.
