### ISSUE TITLE
Buffer variable leaks into global scope

### ISSUE THREAD

**Issue by Srokap** [jstapels/mpu6050#4]
should use `var buffer =` instead of `buffer =`. Also adding `"use strict";` is perhaps worth considering.

I generally caught the issue using mocha in my project for integration testing. Could consider adding here jshint perhaps if you're still interested in this library.

**Comment by jstapels** [comment]
Thanks, I haven't looked at this in awhile but when I get some time I'll add in the strict flag and try to clean it up a bit. Feel free to make a pull request if you've already fixed some issues.

**Comment by Srokap** [comment]
It does not seem to be a problem on main branch anymore.
